### ISSUE TITLE
Mariaex timeout in Phoenix causes failed request

### ISSUE THREAD

**Issue by uzleepito** [xerions/mariaex#101]
I have a Phoenix app that gives an "Internal server error" after it is left alone for many hours, and the MYSQL connection to the server times out.  Further request are working properly after the failing one triggers some supervisor interventions.  I believe this is not the proper behavior, and that first request should be served without error and db reconnection should happen seamlessly.

**Comment by liveforeverx** [comment]
Hi! Which mariaex version?

**Comment by uzleepito** [comment]
mariaex: 0.7.0

phoenix: 1.1.4

phoenix_ecto: 2.0.1

poolboy: 1.5.1

**Comment by liveforeverx** [comment]
@uzleepito Thanks!

**Comment by uzleepito** [comment]
It seems that postgrex does not have the same problem.
Here's what I see on the console when it happens with mariaex:

```
15:18:27.654 request_id=3s7m1dkeei7sbd15oe6eg06ur3eeimm1 [info] GET /
15:18:27.714 [error] Mariaex.Protocol (#PID<0.888.0>) disconnected: ** (Mariaex.Error)
15:18:32.689 request_id=3s7m1dkeei7sbd15oe6eg06ur3eeimm1 [info] Sent 500 in 5034ms
15:18:32.700 [error] #PID<0.4713.0> running CallCenter.Endpoint terminated
Server: xxx.xxx.xxx.xxx:4444 (http)
Request: GET /
** (exit) exited in: :gen_server.call(#PID<0.888.0>, {:checkout, #Reference<0.0.1.178451>, true, 15000}, 5000)
    ** (EXIT) time out
```

**Comment by liveforeverx** [comment]
Hi! Please retest with version: 0.7.1

**Comment by uzleepito** [comment]
Hi, the app seems to be responding now, but I can see this on the console now and then:

```
16:14:13.624 [error] GenServer #PID<0.3781.0> terminating
** (FunctionClauseError) no function clause matching in Mariaex.Protocol.ping_handle/3
    (mariaex) lib/mariaex/protocol.ex:568: Mariaex.Protocol.ping_handle({:packet, 7, 1, {:bin_row, <<0, 0, 0, 2, 0, 0, 0>>}, <<0, 0, 0, 2, 0, 0, 0>>}, :ping, %Mariaex.Protocol{buffer: "", cache: 4718733, catch_eof: false, connection_id: #PID<0.3781.0>, connection_ref: #Reference<0.0.1.117904>, lru_cache: {100, 4722795}, opts: [socket_options: [], sock_type: :tcp, cache_size: 100, timeout: 5000, otp_app: :call_center, repo: CallCenter.Repo, adapter: Ecto.Adapters.MySQL, username: "*****", password: "*******", database: "******", hostname: "*******", port: 3306], protocol57: false, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.50555>}, state: :bin_rows, state_data: {0, 0}, timeout: 5000})
    (db_connection) lib/db_connection/connection.ex:313: DBConnection.Connection.handle_info/2
    (connection) lib/connection.ex:812: Connection.handle_async/3
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

It seems to happen 10-15 seconds after the last HTTP request arrived, so I guess this is some sort of a timeout issue.

**Comment by liveforeverx** [comment]
Please update to `0.7.3` ( related #106 )

**Comment by uzleepito** [comment]
It's perfect.  Thanks for fixing it!
