### ISSUE TITLE
Geo Functions?

### ISSUE THREAD

**Issue by dotdotdotpaul** [xerions/mariaex#124]
There's a hex called [geo](https://github.com/bryanjos/geo) that adds structs for representing OpenGIS models, like Point and Polygon, and has defined macros that generate the OpenGIS SQL fragments.

The macros all seem to work, but I don't see how I can extend Mariaex support in the geo lib to handle the structs as parameters (so you could pass a %Geo.Point{coordinates: {x,y}} argument in, and have it get converted into "Point(x,y)" -- that's where Mariaex fails:

```
* (ArgumentError) query has invalid parameter %Geo.Point{coordinates: {37.79, -122.4}, srid: nil}
     stacktrace:
       (mariaex) lib/mariaex/query.ex:127: DBConnection.Query.Mariaex.Query.encode_param/1
       (mariaex) lib/mariaex/query.ex:79: DBConnection.Query.Mariaex.Query.encode_params/2
       ...
```

I'm still pretty new at the metaprogramming in Elixir, am I missing some easy way to add support for new parameter types to Mariaex without changing the library itself (with an 'extension', as the Geo package is doing for Postgrex)?  If not...  would it be better to try to include the Geo support directly into Mariaex, or better to try to get Mariaex to be more "extensible"?

**Comment by liveforeverx** [comment]
Hi! I'm for second possibility, make it more extensible.

Probably, we need to check, how postgres handles it and make something in the way.

**Comment by liveforeverx** [comment]
I have checked, documentation, there exists `ProtocolBinary::MYSQL_TYPE_GEOMETRY`, till it is not extensible in MySQL / MariaDB, we should support this types natively.

**Comment by liveforeverx** [comment]
This 2 functions are relevant: https://github.com/xerions/mariaex/blob/master/lib/mariaex/query.ex#L100 and this: https://github.com/xerions/mariaex/blob/master/lib/mariaex/query.ex#L194 for decoding/encoding.

Probably we need extensibility for decoding from Point to generic Geometry type and back.

**Comment by alexbredy** [comment]
+1
Any updates?
