### ISSUE TITLE
After upgrading to 0.8.1, I got this when I run mix test

### ISSUE THREAD

**Issue by jackalcooper** [xerions/mariaex#165]
```
** (ArgumentError) cannot load `"20161226133600"` as type :integer
    (ecto) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.load!/3
    (ecto) lib/ecto/adapters/sql.ex:584: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/adapters/sql.ex:577: Ecto.Adapters.SQL.process_row/3
    (mariaex) lib/mariaex/query.ex:168: DBConnection.Query.Mariaex.Query.do_decode/3
    (mariaex) lib/mariaex/query.ex:143: DBConnection.Query.Mariaex.Query.decode/3
    (db_connection) lib/db_connection.ex:1010: DBConnection.decode/6
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
```

I think it's cause by Ecto and ActiveRecord have different types of schema version number. But it works fine when mariaex was at 0.7.3

**Comment by geofflane** [comment]
@jackalcooper Mind sharing your solution to this? I just saw this on a couple of apps running with Elixir 1.4 and Mariaex 0.8.1 as well.

**Comment by jackalcooper** [comment]
Currently I just downgrade Mariaex for now. But I can tell you the real solution to fix it. I read somewhere Jose once said you can change the schema version number's type to int from ActiveRecord side because ActiveRecord is OK with both string and int for this. I didn't do this because my boss won't allow me.

**Comment by jackalcooper** [comment]
I think I should reopen this because I just found it's not just me encountered this.

**Comment by josevalim** [comment]
THis is probably because your database has a migration table where the id is a string but Ecto migration table expects it to be an integer. It is not related to MySQL at all. Dropping your database if possible or picking a different migration table for Ecto should fix it.
