### ISSUE TITLE
Timeout when running migration on a large table

### ISSUE THREAD

**Issue by preciz** [xerions/mariaex#168]
I have a simple migration that I would like to run, just adding a boolean column.
The table is around 16M rows, I already upped the timeout value to 12_000_000.
The error is:

```
alter table my_table

20:16:13.072 [error] Mariaex.Protocol (#PID<0.178.0>) disconnected: ** (Mariaex.Error) [tcp] `recv` failed with: :timeout
** (Mariaex.Error) [tcp] `recv` failed with: :timeout
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/mysql.ex:101: anonymous fn/4 in Ecto.Adapters.MySQL.execute_ddl/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/mysql.ex:101: Ecto.Adapters.MySQL.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
```

How should one deal with this situation?

**Comment by dbhobbs** [comment]
I'm seeing this as well.

May be related to #162.

**Comment by preciz** [comment]
I used this workaround, you might find it temporarily useful:

```
db_timeout = case System.get_env("DB_TIMEOUT") do
               nil -> 30_000
               "infinity" -> :infinity
             end

config :silo, Silo.Repo,
  ...
  timeout: db_timeout

```

To run it for example:
`MIX_ENV=prod DB_TIMEOUT=infinity mix ecto.migrate --env=prod`
