### ISSUE TITLE
0.8.1 incompatibility with ecto 2.1.3 (Solved NOT an issue)

### ISSUE THREAD

**Issue by paulgithub** [xerions/mariaex#169]
When running a test using mariaex 0.8.1 and ecto 2.1.3 I get the following error:

> ** (Protocol.UndefinedError) protocol String.Chars not implemented for %Mariaex.Query{binary_as: :field_type_var_string, name: "", num_params: 50, ref: #Reference<0.0.7.943>, reserved?: false, statement: "INSERT INTO `accounts` (...) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", type: :binary}
     stacktrace:
       (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
       (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
       (ecto) lib/ecto/adapters/sql.ex:653: Ecto.Adapters.SQL.log/4
       (db_connection) lib/db_connection.ex:1177: DBConnection.log/6
       (ecto) lib/ecto/adapters/mysql/connection.ex:22: Ecto.Adapters.MySQL.Connection.execute/4
       (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
       (ecto) lib/ecto/adapters/mysql.ex:179: Ecto.Adapters.MySQL.insert/6
       (ecto) lib/ecto/repo/schema.ex:467: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:205: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:131: Ecto.Repo.Schema.insert!/4
       test...

If I run the same test using mariaex 0.8.1 and ecto 2.1.2 everything works fine. The same thing happens with many tests. The line in my code causing the problem is a simple Repo.insert! function.

My temporary solution is to set ecto to 2.1.2 (using: {:ecto, "2.1.2"}) in my mix.exs file rather than using {:ecto, "~> 2.1"}

**Comment by paulgithub** [comment]
Actually the above was not the issue.

I was in an umbrella project and the creation of a new application within the project caused the issue. Even though the new application had no reference with the application which contained the Ecto code in the initial post.

The solution is to force a recompilation of all the code before running the tests again. This can be achieved by explicitly changing the ecto version in the mix.exs file run:

$ mix.deps.update ecto

followed by:

$ mix test

Then change the ecto version back again and run the two commands above again.

This is strange and I have no idea as to what may be causing it.
