### ISSUE TITLE
Error running mariaex query on date column

### ISSUE THREAD

**Issue by nathanjohnson320** [xerions/mariaex#62]
I am using ecto with the mariaex adapter and when I run this query
```
SELECT L0.`dialeraddeddate` FROM `Test` AS L0 WHERE (L0.`id` = 1)
```

I get the following error:
```
** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: <<0>>
            (mariaex) lib/mariaex/messages.ex:336: Mariaex.Messages.parse_date_packet/1
            (mariaex) lib/mariaex/messages.ex:281: Mariaex.Messages.decode_bin_rows/4
            (mariaex) lib/mariaex/protocol.ex:96: Mariaex.Protocol.dispatch/2
            (mariaex) lib/mariaex/connection.ex:219: Mariaex.Connection.process/2
            (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
            (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (ecto) lib/ecto/adapters/mysql/connection.ex:31: Ecto.Adapters.MySQL.Connection.query/4
    (ecto) lib/ecto/adapters/sql/worker.ex:24: Ecto.Adapters.SQL.Worker.query!/4
    (ecto) lib/ecto/adapters/sql.ex:187: Ecto.Adapters.SQL.use_worker/3
    (person) lib/person.ex:2: Person.Repo.log/2
    (ecto) lib/ecto/adapters/sql.ex:381: Ecto.Adapters.SQL.all/5
    (ecto) lib/ecto/repo/queryable.ex:20: Ecto.Repo.Queryable.all/4
```

The column is a MySQL date type set to be not null with a default value of 0000-00-00. Somehow the packet is getting a value of <<0>> I'm just not sure how.

**Comment by liveforeverx** [comment]
Thanks for reporting, it is because MySQL binary protocol for 0000-00-00 sends simple 0. Fixed on master.
