### ISSUE TITLE
Support for "secure_auth: false"

### ISSUE THREAD

**Issue by shadabahmed** [xerions/mariaex#72]
Connection cannot be established, when secure auth it turned off at the server. It fails with this error:

```
 ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: <<254>>
                (mariaex) lib/mariaex/messages.ex:118: Mariaex.Messages.decode_eof_resp/1
                (mariaex) lib/mariaex/messages.ex:254: Mariaex.Messages.decode/2
                (mariaex) lib/mariaex/connection.ex:251: Mariaex.Connection.process/2
                (mariaex) lib/mariaex/connection.ex:222: Mariaex.Connection.handle_info/2
                (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
                (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
                (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

I checked on the server for the secure auth setting:

```
> show variables like "%auth%";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| secure_auth   | OFF   |
+---------------+-------+
```

In this case even `mysql` client cli needs `--skip-secure-auth` without which it gets the following error:
```
ERROR 2049 (HY000): Connection using old (pre-4.1.1) authentication protocol refused (client option 'secure_auth' enabled)
```

Can we add the support for this ? 

Found reference on how to fix this here - https://www.safaribooksonline.com/library/view/understanding-mysql-internals/0596009577/ch04s04.html

**Comment by liveforeverx** [comment]
It something not related to secure_auth, as I have the same settings:

```
MariaDB [(none)]> show variables like "%auth%";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| secure_auth   | OFF   |
+---------------+-------+
```

Can you provide MySQL version and settings, which causes the following error?

The problem, which you see is the next message, which MySQL sends is EOF packet, which doesn't have flags. 

> In the pre-4.1 era, there was nothing else in the body in addition to this byte. Version 4.1 added another 4 bytes of status fields ( reference: https://www.safaribooksonline.com/library/view/understanding-mysql-internals/0596009577/ch04s06.html )

Which version of Mysql do you want to use??

**Comment by shadabahmed** [comment]
My version string:
```
Your MySQL connection id is 18175622
Server version: 5.6.21-enterprise-commercial-advanced-log MySQL Enterprise Server - Advanced Edition (Commercial)
```

There are some changes related to `secure_auth` being default in versions [5.6.7+](http://dev.mysql.com/doc/refman/5.6/en/mysql-command-options.html#option_mysql_secure-auth) but this error is more related to handshake implementation.

The packet is not `eof` packet. As mentioned in the *Auth Handshake* reference [here](https://www.safaribooksonline.com/library/view/understanding-mysql-internals/0596009577/ch04s04.html):

```
The third possibility comes from the need to support the transition from 4.0 to 4.1. In some cases,
 the DBA may have upgraded both the client and the server to 4.1, but forgot or chose not to upgrade
 the user table in the mysql database, which contains user names and their respective password 
hashes. If the entry for that user has the old-style password hash, it is impossible to authenticate 
with the new authentication protocol.

In that event, the server sends a special packet with the 1-byte-long body containing decimal 254, 
which means: "please send the authentication credentials in the old format." The client responds 
with a packet whose body contains a zero-terminated encrypted password string. The server 
responds with either OK or a standard error message.
```

I also looked at other libraries for implementation of this case. The node-mysql lib handles this case in the [handshake module](https://github.com/felixge/node-mysql/blob/de5913227dbbaacbbdf22ee38689d090e1451be9/lib/protocol/sequences/Handshake.js#L27
)

if especially checks for `<<254>>` byte and then resends the password hash using the older algorithm.

**Comment by liveforeverx** [comment]
Thanks for clarification, I'll try to install new version of MySQL and test it.

**Comment by liveforeverx** [comment]
Would be nice, if it possible to provide .travis configuration for testing this case, thats would help a much.

**Comment by shadabahmed** [comment]
i will try to add .. i think we can replicate it by setting user password using the `OLD_PASSWORD()` mysql fn . .and then try to authenticate

**Comment by shadabahmed** [comment]
This is how replicated on my local mysql:

* Created user:
```
GRANT ALL ON *.* to `testuser`@`localhost` identified by 'testpwd';
```
* Tried authenticating as the new user:
```
$mysql -u testuser -ptestpwd
#works
```
* Change user password plugin and hash:
```
update mysql.user set password = OLD_PASSWORD('testpwd'), plugin = "mysql_old_password" where user = "testuser";
```
* Tried authenticating again:
```
mysql -u testuser -ptestpwd                                                                                   ruby-2.2.1  ✘ 1
Warning: Using a password on the command line interface can be insecure.
ERROR 2049 (HY000): Connection using old (pre-4.1.1) authentication protocol refused (client option 'secure_auth' enabled)

mysql -u testuser -ptestpwd --skip-secure-auth 
# works
```





```

**Comment by liveforeverx** [comment]
Many thanks for helping reproduce it. I'll definitely test it this weekend.

**Comment by shadabahmed** [comment]
were you able to work on this bug ?

**Comment by liveforeverx** [comment]
@shadabahmed - sorry, I was away for a more weeks, I wasn't able to work, but will work this weekend. Sorry for such long time.
